upstream backend {
   server backend:8080
}

server {
   listen 80 ;
   listen [::]:80
   location / {
      root /usr/share/nginx/html;
      index index.html;
      try_file $uri /index.html
   }
   location /api {
      proxy_pass http://backend;
   }
   location /kw2/ {
      proxy_pass http://backend;
   }
}