server {
   listen 80;
   location / {
      root /usr/share/nginx/html;
      index index.html index.html;
   }
   location /api {
      proxy_pass http://backend:8080;
   }
   location /kw2/ {
      proxy_pass http://backend:8080;
   }
}