server {
   listen 80;
      server_name http://intproj21.sit.kmutt.ac.th/kw2/
   location / {
      root /usr/share/nginx/html;
      index index.html index.html;
   }
   location /api {
      proxy_pass backend:8080;
   }
   location /kw2/ {
      proxy_pass backend:8080;
   }
   location /kw2/api {
      proxy_pass backend:8080;
   }
}